### ISSUE TITLE
Can not open Nota on MacOS Catalina

### ISSUE THREAD

**Issue by dakics** [notaapp/releases#1]
Hi,

After downloading the latest 0.22.0 (and any previous release) on MacOS Catalina, I'm getting the "App can not be opened" popup. 

After `chmod +x /Applications/Nota.app/Contents/MacOS/Nota` (found similar issue online for non-notarized apps), I'm getting a different popup: "App can not be opened because it's damaged".

Solution applied here didn't help:

https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t

```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Nota.app/Contents/MacOS/Nota
  Reason: no suitable image found.  Did find:
	/Applications/Nota.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Nota.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
```

There are no options in the System/Security, where I would confirm that I do in fact want to start app downloaded from internet.

App works fine on on MacOS Mojave.

**Comment by astoilkov** [comment]
Hi,

Where did you download Nota from? Downloading it from here won't work. We intentionally break these releases.

If you want to download the latest version go to https://nota.md and fill in the Request Invite form. We will email you a download link shortly after.

**Comment by dakics** [comment]
Yes, I've downloaded it from here. Got it working now.

Thank you for the quick response!
